# -*- coding: utf-8 -*-
"""streamit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQr6C4yvw9eAQ6uqWPPGYyt2YJcoOKPj
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# ฟังก์ชันสำหรับโหลดข้อมูล
@st.cache
def load_data(file):
    df = pd.read_csv(file)
    return df

# ฟังก์ชันสำหรับ Train และ Evaluate โมเดล
def train_and_evaluate(df):
    # ตรวจสอบว่า RGB อยู่ในช่วง 0-255 และ Normalize
    X = df[['R', 'G', 'B']] / 255.0
    y = df['season']

    # แปลง Labels เป็นตัวเลข
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    # แบ่งข้อมูล Train, Validation, Test
    X_train, X_temp, y_train, y_temp = train_test_split(X, y_encoded, test_size=0.3, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

    # ปรับขนาดข้อมูล
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)
    X_test = scaler.transform(X_test)

    # สร้างโมเดล SVM และ Train
    svm_model = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
    svm_model.fit(X_train, y_train)

    # Evaluate บน Validation Set
    y_val_pred = svm_model.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)

    # Evaluate บน Test Set
    y_test_pred = svm_model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    conf_matrix = confusion_matrix(y_test, y_test_pred)

    return val_accuracy, test_accuracy, conf_matrix, label_encoder.classes_, y_test_pred, y_test

# ส่วน UI หลักของ Streamlit
def main():
    st.title("Personal Color Classifier")
    st.write("Upload your dataset to train and evaluate the SVM model.")
    st.write("Make sure your CSV file contains columns named 'R', 'G', 'B', and 'season'.")

    # อัปโหลดไฟล์ CSV
    uploaded_file = st.file_uploader("Upload a CSV file", type="csv")

    if uploaded_file is not None:
        # โหลดข้อมูล
        df = load_data(uploaded_file)
        st.write("Dataset Preview:")
        st.dataframe(df.head())

        # ตรวจสอบคอลัมน์ที่ต้องการ
        required_columns = {'R', 'G', 'B', 'season'}
        if not required_columns.issubset(df.columns):
            st.error(f"The uploaded file must contain the following columns: {', '.join(required_columns)}")
            return

        if st.button("Train and Evaluate Model"):
            st.write("Training the model...")
            val_accuracy, test_accuracy, conf_matrix, class_labels, y_test_pred, y_test = train_and_evaluate(df)

            st.write(f"Validation Accuracy: {val_accuracy:.2f}")
            st.write(f"Test Accuracy: {test_accuracy:.2f}")

            # Confusion Matrix Visualization
            st.write("Confusion Matrix:")
            fig, ax = plt.subplots()
            sns.heatmap(conf_matrix, annot=True, cmap='Blues', xticklabels=class_labels, yticklabels=class_labels, ax=ax)
            plt.xlabel("Predicted")
            plt.ylabel("Actual")
            plt.title("Confusion Matrix")
            st.pyplot(fig)

            # เพิ่ม Classification Report
            st.write("Classification Report:")
            report = classification_report(y_test, y_test_pred, target_names=class_labels, output_dict=True)
            st.dataframe(pd.DataFrame(report).transpose())

if __name__ == "__main__":
    main()